name: 'Deploy OpenTelemetry'
on:
  push:
    branches: main
    paths:
      - .github/workflows/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-otel-job
    permissions:
      actions: read
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@v5.43.1
        with:
          secrets_to_redact: '["${{ github.token }}","${{ secrets.ACTIONS_GITHUB_TOKEN }}","${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}","${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}"]'
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
      - uses: plengauer/opentelemetry-github/actions/instrument/deploy@v5.43.1
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          job_level_instrumentation_exclude: 'Refresh Demos,Shell,GitHub,Workflow Example,Experiment'
          repository_level_instrumentation: true
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
